from enum import Enum


class Knife(Enum):
    BUTTERFLY = "weapon_knife_butterfly"
    M9_BAYONET = "weapon_knife_m9_bayonet"
    KARAMBIT = "weapon_knife_karambit"
    SKELETON = "weapon_knife_skeleton"
    BAYONET = "weapon_bayonet"
    TALON = "weapon_knife_widowmaker"
    NOMAD = "weapon_knife_outdoor"
    FLIP = "weapon_knife_flip"
    STILETTO = "weapon_knife_stiletto"
    CLASSIC = "weapon_knife_css"
    URSUS = "weapon_knife_ursus"
    HUNTSMAN = "weapon_knife_tactical"
    PARACORD = "weapon_knife_cord"
    SURVIVAL = "weapon_knife_canis"
    FALCHION = "weapon_knife_falchion"
    SHADOW_DAGGERS = "weapon_knife_push"
    BOWIE = "weapon_knife_survival_bowie"
    GUT = "weapon_knife_gut"
    NAVAJA = "weapon_knife_gypsy_jackknife"


class Gun(Enum):
    NONE = "weapon_none"
    DEAGLE = "weapon_deagle"
    DUAL_BERETTAS = "weapon_elite"
    FIVESEVEN = "weapon_fiveseven"
    GLOCK = "weapon_glock"
    P228 = "weapon_p228"
    USP = "weapon_usp"
    AK47 = "weapon_ak47"
    AUG = "weapon_aug"
    AWP = "weapon_awp"
    FAMAS = "weapon_famas"
    G3SG1 = "weapon_g3sg1"
    GALIL = "weapon_galil"
    GALILAR = "weapon_galilar"
    M249 = "weapon_m249"
    M3 = "weapon_m3"
    M4A1 = "weapon_m4a1"
    MAC10 = "weapon_mac10"
    MP5NAVY = "weapon_mp5navy"
    P90 = "weapon_p90"
    SCOUT = "weapon_scout"
    SG550 = "weapon_sg550"
    SG552 = "weapon_sg552"
    TMP = "weapon_tmp"
    UMP45 = "weapon_ump45"
    XM1014 = "weapon_xm1014"
    BIZON = "weapon_bizon"
    MAG7 = "weapon_mag7"
    NEGEV = "weapon_negev"
    SAWEDOFF = "weapon_sawedoff"
    TEC9 = "weapon_tec9"
    TASER = "weapon_taser"
    HKP2000 = "weapon_hkp2000"
    MP7 = "weapon_mp7"
    MP9 = "weapon_mp9"
    NOVA = "weapon_nova"
    P250 = "weapon_p250"
    SCAR17 = "weapon_scar17"
    SCAR20 = "weapon_scar20"
    SG556 = "weapon_sg556"
    SSG08 = "weapon_ssg08"


class Glove(Enum):
    SPORT = "weapon_sport_gloves"
    SPECIALIST = "weapon_specialist_gloves"
    MOTO = "weapon_moto_gloves"
    DRIVER = "weapon_driver_gloves"
    HAND_WRAPS = "weapon_hand_wraps"
    BROKEN_FANG = "weapon_brokenfang_gloves"
    HYDRA = "weapon_hydra_gloves"
    BLOODHOUND = "weapon_bloodhound_gloves"


class Agent(Enum):
    CT_AGENT = "agent_team_ct"
    T_AGENT = "agent_team_t"


class Sticker(Enum):
    PARIS_2023 = "sticker_tournament21"
    ESPIONAGE = "crate_sticker_pack_community2022_capsule"
    RIO_2022 = "crate_sticker_pack_rio2022_capsule"
    CSGO_10 = "crate_sticker_pack_csgo10_capsule"
    ANTWERP_2022 = "crate_sticker_pack_antwerp2022_capsule"
    BOARDROOM = "crate_sticker_pack_spring2022_capsule"
    BF2042 = "crate_sticker_pack_bf2042_capsule_lootlist"
    STOCKHOLM_2021 = "crate_sticker_pack_stockholm2021_capsule"
    RIPTIDE_SURF_SHOP = "crate_sticker_pack_riptide_surfshop_lootlist"
    OPERATION_RIPTIDE = "crate_sticker_pack_op_riptide_capsule_lootlist"
    COMMUNITY_2021 = "crate_sticker_community2021_capsule"
    POORLY_DRAWN = "poorly_drawn"
    RMR_2020 = "sticker_2020rmr"
    BROKEN_FANG = "sticker_broken_fang"
    RECOIL = "sticker_recoil"
    WARHAMMER_40K = "warhammer_sticker"
    HL_ALYX = "alyx_sticker_capsule"
    HALO = "halo_capsule"
    SHATTERED_WEB = "shattered_web"
    CS20 = "cs20_capsule"
    BERLIN_2019 = "2019_StarLadder_Berlin_Major"
    CHICKEN = "crate_sticker_pack_chicken_capsule_lootlist"
    FERAL_PREDATORS = "crate_sticker_pack_feral_predators_capsule_lootlist"
    KATOWICE_2019 = "sticker_tournament15"
    SKILL_GROUP = "skill_groups_capsule"
    LONDON_2018 = "sticker_tournament14"
    BOSTON_2018 = "sticker_tournament13"
    KRAKOW_2017 = "sticker_tournament12"
    ATLANTA_2017 = "sticker_tournament11"
    COLOGNE_2016 = "sticker_tournament10"
    COLUMBUS_2016 = "sticker_tournament9"
    DREAMHACK_2015 = "sticker_tournament8"
    COLOGNE_2015 = "sticker_tournament7"
    KATOWICE_2015 = "sticker_tournament6"
    DREAMHACK_2014 = "sticker_tournament5"
    COLOGNE_2014 = "sticker_tournament4"
    KATOWICE_2014 = "sticker_tournament3"
    COMMUNITY_2018 = "crate_sticker_pack_comm2018_01_capsule_lootlist"
    STICKER_1 = "crate_sticker_pack01"
    STICKER_2 = "crate_sticker_pack02"
    ENFU_STICKERS = "crate_sticker_pack_enfu_capsule_lootlist"
    PERFECT_WORLD_1 = "crate_sticker_pack_illuminate_capsule_01_lootlist"
    PERFECT_WORLD_2 = "crate_sticker_pack_illuminate_capsule_02_lootlist"
    COMMUNITY_1 = "crate_sticker_pack_community01"
    BESTIARY = "crate_sticker_pack_bestiary_capsule_lootlist"
    SLID3 = "crate_sticker_pack_slid3_capsule_lootlist"
    SUGARFACE = "crate_sticker_pack_sugarface_capsule_lootlist"
    PINUPS = "crate_sticker_pack_pinups_capsule_lootlist"
    TEAM_ROLES = "crate_sticker_pack_team_roles_capsule_lootlist"
    OTHER_STICKERS = "sticker_other"


class OtherItem(Enum):
    WEAPON_CASE = "csgo_type_weaponcase"
    MUSIC_KIT = "csgo_type_musickit"
    TOOL = "csgo_type_tool"
    SPRAY = "csgo_type_spray"
    TICKET = "csgo_type_ticket"
    COLLECTIBLE = "csgo_type_collectible"
    PATCH = "csgo_tool_patch"
    GIFT_TAG = "csgo_tool_gifttag"
    WEAPON_CASE_KEY_TAG = "csgo_tool_weaponcase_keytag"
